### PR TITLE
CORE-46: Allow multiple configurable anonymous-http-access mappings

### PR DESCRIPTION
**Pull request by ianmcorvidae**
This should make it be just config changes to switch our anonymous access over to using WebDAV. The configuration I used to test this (against prod, as there's no webdav in QA at present) is:

```
data-info.anon-files-mappings        = {"/iplant/home/shared/": "https://data.cyverse.org/dav-anon/iplant/projects/", "/iplant/home/shared/commons_repo/curated/": "https://data.cyverse.org/dav-anon/iplant/commons/cyverse_curated/", "/iplant/home/": "https://data.cyverse.org/dav-anon/iplant/home/"}
```

### CODE REVIEW

**Comment by ianmcorvidae** [comment]
Heh, yeah. In my defense, we already put JSON in both the apps and the UI properties files :see_no_evil:

**Comment by slr71** [comment]
Yeah, that's a good point. My suggestion wasn't meant to be disparaging in any way. I was just thinking that it might be nice to have an easier way to add mappings like this.

**Comment by ianmcorvidae** [comment]
Nah, you're right. This'll do for now though (as you also said!).

... maybe mostly I wanted to make the :see_no_evil: joke ...

**Comment by tedgin** [comment]
The service's base URL, e.g., https://data.cyverse.org/dav-anon, should be externalized as its on configuration value.  This allows the service to be relocatable without having to change the path mappings. Other than that, it looks good to me.

**Comment by ianmcorvidae** [comment]
Hm. I'd avoided doing that deliberately, because I was thinking we might ultimately want to be able to use multiple systems for this (for a concrete idea: what if cyverse-uk wants to run a WebDAV server for accessing data on their resource server more efficiently than it roundtripping via ours). Not sure if that's overthinking it, though. What do you think, @tedgin ?

**Comment by tedgin** [comment]
Wouldn't having the service's base URL be its own config value facilitate having different locations be able to use different WebDAV servers?  Only a single value would need to be changed, the base URL. It could even be passed a parameter to data-info as part of the request. I'm guessing that I'm misunderstanding your point.

**Comment by ianmcorvidae** [comment]
Ah, I'd meant if they're both using the same DE/the same data-info config. Basically, for the people who are using us for data management, but running their own resource server(s) for locality and probably running their own analyses (at least until we can route their analyses close to their data in the DE). They'd need this configuration to be in the same instance of data-info, but point to a different server for the data they want to get easier access to. I'm assuming here that the way the WebDAV server is set up, it would not have to roundtrip via the IES (other than for metadata/etc.) in order to serve up a data file from a resource server.

To be as clear as I know how:
* 1 ICAT
* 1 IES
* 1 DE/data-info (well, several, but same config)
* N resource servers, with 1 or more located a large distance from the ICAT/IES
* 2 WebDAV servers, one near the ICAT/IES, one near the remote resource server

When users whose data resides on the remote resource server wish to access that data over HTTP, they should use the WebDAV server nearer to the remote resource server, so when the DE, via data-info, is providing them a URL to use, it should ideally use that server's address. If the division between resource servers is apparent from the filesystem layout (e.g. if all of a given project's folder reside on the same remote resource server), then these mappings can facilitate providing the correct address, but only if we support a single data-info instance generating URLs from several different base WebDAV URLs (or other systems, even, potentially).

**Comment by tedgin** [comment]
I understand now. It feels like you are adding something to the DE that should really be part of the Data Store. Ideally, we could have the proxy use the requested path and/or the geo ip info of the client to redirect the request to the appropriate WebDAV server. This would allow data to be moved to and from remote resource servers and still keep the same URL. Using redirects results in a small performance hit though. I don't know how substantial that would end up being.

**Comment by ianmcorvidae** [comment]
Hm, yeah, that's probably fair. I'll externalize that base URL and make the path mappings relative to it, then. Thanks!

**Comment by ianmcorvidae** [comment]
Cool, thanks for the reviews. I'll get the changes ready in our configurations and then merge this once that part's ready.

**Pull request merged**
